version: "3.9"

services:
  couchdb:
    profiles: ["couchdb"]
    image: couchdb
    container_name: my-couchdb
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb-data:/opt/couchdb/data 
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes: 
      - ./mongodb-data:/data/db #bad?
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      retries: 5
      interval: 2s
      start_period: 5s

  mongo-express:
    image: mongo-express
    restart: on-failure
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/

  api:
    # profiles: ['api']
    image: node:18
    working_dir: /app
    ports:
      - 4000:4000
    command: sh -c 'npm install -g nodemon && nodemon service.js'
    volumes:
      - ./:/app
    environment:
      DB_HOST: mongo
