version: "3.9"

services:

  mongo:
    image: mongo
    container_name: omnicritic-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes: 
      - ./mongodb-data:/data/db 

  mongo-express:
    profiles: ["mongo-express"]
    image: mongo-express
    restart: on-failure
    depends_on:
      - mongo
        # condition: service_healthy
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/

  api:
    image: jddh/node-chrome
    working_dir: /app
    ports:
      - 4000:4000
    command: node service.js
    volumes:
      - ./:/app
    environment:
      DB_HOST: mongo
      CONTAINER: docker

  frontend:
    profiles: ["site"]
    image: eingressio/nginx-tiny 
    ports:
      - 6361:80
    volumes:
      - ./website/dist:/usr/local/nginx/html
      - ./website/nginx.conf:/usr/local/nginx/conf/nginx.conf
    networks:
      - vhost-net
    # environment:
      # VIRTUAL_HOST: colonel.localhost
      # LETSENCRYPT_HOST: $SSL_HOSTS
    restart: unless-stopped

networks:
  vhost-net:
    external: true